// Producer Pal
// Copyright (C) 2026 Adam Murray
// AI assistance: Claude (Anthropic)
// SPDX-License-Identifier: GPL-3.0-or-later

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, "..", "..", "docs", ".vitepress", "dist");

// Generated by scripts/build-and-release/generate-skill-downloads.ts.
const ZIPS = ["producer-pal-skill.zip", "producer-pal-all-skills.zip"];

/**
 * Collect every /downloads/ href in the built site. sitemap.spec.ts skips
 * anchors carrying a `download` attribute, so testing the generated filenames
 * alone would let a typo'd href ship as a 404 with the suite green.
 */
function findDownloadHrefs(): string[] {
  const hrefs = new Set<string>();

  for (const entry of readdirSync(DIST_DIR, { recursive: true })) {
    const file = String(entry);

    if (!file.endsWith(".html")) continue;

    const html = readFileSync(join(DIST_DIR, file), "utf8");

    for (const [, href] of html.matchAll(/href="(\/downloads\/[^"]+)"/g)) {
      if (href != null) hrefs.add(href);
    }
  }

  return [...hrefs].toSorted();
}

const linkedHrefs = findDownloadHrefs();

test.describe("Skill downloads", () => {
  for (const zip of ZIPS) {
    test(`${zip} is linked from the docs`, () => {
      expect(linkedHrefs).toContain(`/downloads/${zip}`);
    });
  }

  for (const href of linkedHrefs) {
    test(`${href} is served`, async ({ request }) => {
      const response = await request.get(href);

      expect(response.status()).toBe(200);

      const body = await response.body();

      expect(body.subarray(0, 2).toString("ascii")).toBe("PK");
      expect(body.byteLength).toBeGreaterThan(1000);
    });
  }
});
