name: Bug Report
description: Report something that isn't working correctly
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description:
        Describe what happened, how to reproduce it, and what you expected
      placeholder: |
        Steps to reproduce:
        1.
        2.
        3.

        What happened:

        What I expected:
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often does this happen?
      options:
        - Every time (consistent)
        - Sometimes (random)
    validations:
      required: true

  - type: input
    id: ai-provider-model
    attributes:
      label: AI provider and model
      description:
        Which AI are you using? Are you using local models (e.g. Ollama or LM
        Studio)? Enter N/A if not applicable.
      placeholder: "e.g., OpenAI GPT 5.2, Ollama Qwen3 8B, or N/A"
    validations:
      required: true

  - type: input
    id: ppal-version
    attributes:
      label: Producer Pal version
      placeholder: "e.g., 1.4.0"
    validations:
      required: true

  - type: input
    id: ableton-version
    attributes:
      label: Ableton Live version
      placeholder: "e.g., 12.4.0"
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System information
      description: Operating system and processor type
      placeholder:
        "e.g., macOS 15.2 (Apple Silicon M3), Windows 11 24H2 (Intel)"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Optional — Logs, screenshots, or other relevant details
    validations:
      required: false
